WebAnalytics.Presentation.UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using WebAnalytics.Presentation.ViewModels;
using WebAnalytics.UI.Middleware;
using WebAnalytics.UI.Models;

namespace WebAnalytics.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMemoryCache _memoryCache;

        public HomeController(IMemoryCache memoryCache)
        {
            _memoryCache = memoryCache;
        }

        public IActionResult Index()
        {
            return View(new HomeViewModel { UserCount = TrackingMiddleware.OnlineClients.Count, SessionId = HttpContext.Session.Id, UserInfo = _memoryCache.Get<string>(HttpContext.Session.Id) });
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Dashboard()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAnalytics.Presentation.UI/Controllers/ReportGeneratorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using WebAnalytics.Services.Interfaces;

namespace WebAnalytics.Presentation.UI.Controllers
{
    public class ReportGeneratorController : Controller
    {
        private readonly IStatisticsService _statisticsService;

        public ReportGeneratorController(IStatisticsService statisticsService)
        {
            _statisticsService = statisticsService;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult TotalStatistics()
        {
            byte[] fileContents;

            using (var package = new ExcelPackage())
            {
                var row = 1;
                var worksheet = package.Workbook.Worksheets.Add("Sheet1");

                var totalStatistics = _statisticsService.GetTotalStatistics();
                worksheet.Cells[row, 1].Value = "Total users";
                worksheet.Cells[row++, 2].Value = totalStatistics.TotalUsersCount;
                worksheet.Cells[row, 1].Value = "Total page views count";
                worksheet.Cells[row++, 2].Value = totalStatistics.TotalPageViewsCount;
                worksheet.Cells[row, 1].Value = "Total clicks";
                worksheet.Cells[row++, 2].Value = totalStatistics.TotalClicksCount;
                row++;
                var deviceUsage = _statisticsService.GetDeviceUsageStatistics();
                worksheet.Cells[row, 1].Value = "Device usage statistics";
                worksheet.Cells[row++, 1].Style.Font.Bold = true;
                for (int i = 0; i < deviceUsage.Count; i++)
                {
                    worksheet.Cells[row, 1].Value = deviceUsage[i].Device;
                    worksheet.Cells[row++, 2].Value = deviceUsage[i].Count;
                }
                row++;
                var pageViewStatistics = _statisticsService.GetPageViewStatistics();
                worksheet.Cells[row, 1].Value = "Page view statistics";
                worksheet.Cells[row++, 1].Style.Font.Bold = true;
                for (int i = 0; i < pageViewStatistics.Count; i++)
                {
                    worksheet.Cells[row, 1].Value = pageViewStatistics[i].Url;
                    worksheet.Cells[row++, 2].Value = pageViewStatistics[i].Count;
                }
                row++;
                var clickStatistics = _statisticsService.GetClickStatistics();
                worksheet.Cells[row, 1].Value = "Click statistics";
                worksheet.Cells[row++, 1].Style.Font.Bold = true;
                for (int i = 0; i < pageViewStatistics.Count; i++)
                {
                    worksheet.Cells[row, 1].Value = clickStatistics[i].Description;
                    worksheet.Cells[row++, 2].Value = clickStatistics[i].Count;
                }

                fileContents = package.GetAsByteArray();
            }

            if (fileContents == null || fileContents.Length == 0)
            {
                return NotFound();
            }

            return File(
                fileContents: fileContents,
                contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                fileDownloadName: "test.xlsx"
            );
        }
    }
}

WebAnalytics.Presentation.UI/Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<link rel="stylesheet" type="text/css" href="~/lib/chart/Chart.min.css">

<h1>Dashboard</h1>

<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="realtime-tab" data-toggle="tab" href="#realtime" role="tab" aria-controls="realtime" aria-selected="true">Realtime</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="total-tab" data-toggle="tab" href="#total" role="tab" aria-controls="total" aria-selected="false">Total</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="behaiviour-tab" data-toggle="tab" href="#behaiviour" role="tab" aria-controls="behaiviour" aria-selected="false">Behaivour</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="realtime" role="tabpanel" aria-labelledby="realtime-tab">
        <h3>Online users: <span id="onlineClientsCount"></span></h3>
        <div class="table-responsive">
            <table id="onlineClients" class="table table-bordered ">
                <thead></thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
    <div class="tab-pane fade" id="total" role="tabpanel" aria-labelledby="total-tab">
        <h3>Total statistics</h3>
        <a asp-controller="ReportGenerator" asp-action="TotalStatistics">Download report</a>
        <h4>Total users: <span id="totalUniqueUsersCount" /></h4>
        <h4>Total page views: <span id="totalPageViewsCount" /></h4>
        <h4>Total clicks: <span id="totalClicksCount" /></h4>
        <h3>All clients</h3>
        <div class="table-responsive">
            <table id="clients" class="table table-bordered ">
                <thead></thead>
                <tbody></tbody>
            </table>
            <div class="paginator"></div>
        </div>
        <h3>Device usage</h3>
        <canvas id="deviceUsage" width="600" height="400"></canvas>
    </div>
    <div class="tab-pane fade" id="behaiviour" role="tabpanel" aria-labelledby="behaiviour-tab">
        <h3>All actions</h3>
        <div class="table-responsive">
            <table id="actions" class="table table-bordered ">
                <thead></thead>
                <tbody></tbody>
            </table>
            <div class="paginator"></div>
        </div>
        <h3>Daily views</h3>
        <canvas id="dailyViews" width="600" height="400"></canvas>
        <h3>Page views</h3>
        <div class="table-responsive">
            <table id="pageViews" class="table table-bordered ">
                <thead></thead>
                <tbody></tbody>
            </table>
        </div>
        <h3>Clicks count</h3>
        <div class="table-responsive">
            <table id="clicks" class="table table-bordered ">
                <thead></thead>
                <tbody></tbody>
            </table>
        </div>
        <h3>Average time on page</h3>
        <div class="table-responsive">
            <table id="averageTimeOnPage" class="table table-bordered ">
                <thead></thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/chart/Chart.min.js" asp-append-version="true"></script>
    <script src="~/js/dashboard.js" asp-append-version="true"></script>
}

WebAnalytics.Presentation.UI/Views/Home/Index.cshtml
@model WebAnalytics.Presentation.ViewModels.HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <div class="track btn btn-outline-primary" data-description="search">Search</div>
    <div class="track btn btn-outline-primary" data-description="help">Help</div>
    <div class="track btn btn-outline-primary" data-description="more">More</div>
</div>
@section Scripts {
    <script src="~/js/actionMonitor.js" asp-append-version="true"></script>
}